### ISSUE TITLE
Gentoo linux

### ISSUE THREAD

**Issue by aspann** [Eein/zephyrus-g14#1]
Hey there,

this is not really an Issue - I'm currently busy fixing kernel-stuff etc.  for our Gentoo installations. I just want to ask if we make any progress over here, should we share it? Like BIOS information, firmwares, etc.

cheers.

**Comment by Eein** [comment]
It might be easier to compile the information somewhere and I'd be happy to link to it :) 
If that's too much work, I can likely find a place for in this repo.

I'm currently using this repo as a personal testbed for any tips and tricks while trying to get things stable and toy with getting the keyboard keys to work. 

Thanks!

**Comment by aspann** [comment]
Hi, 
thanks for your answer. I'm also currently busy putting all the informations together. As soon as we made a repo for that, I'll inform you.

Btw. keybord keys: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1802652/comments/23

cheers.

**Comment by Eein** [comment]
Addition discussion at https://github.com/flukejones/rog-core/issues/3

**Comment by aspann** [comment]
Thanks for the info, here my asus-wmi/asus-nb-wmi patch.. (keys not working, but thermalzone is settable - so no safty shutdown if >95 °C)

```diff
--- a/drivers/platform/x86/asus-wmi.c
+++ b/drivers/platform/x86/asus-wmi.c
@@ -116,6 +116,8 @@
        u32 arg0;
        u32 arg1;
        u32 arg2; /* At least TUF Gaming series uses 3 dword input buffer. */
+       u32 arg3; /* At least ROG Zephyrus uses 5 dword input buffer */
+       u32 arg4;
 } __packed;
 
 /*
--- a/drivers/platform/x86/asus-nb-wmi.c
+++ b/drivers/platform/x86/asus-nb-wmi.c
@@ -110,6 +110,12 @@
        .wmi_force_als_set = true,
 };
 
+static struct quirk_entry quirk_asus_ga401iv = {
+       .wapf = 4,
+       .wmi_backlight_power = true,
+       .wmi_backlight_set_devstate = true,
+};
+
 static int dmi_matched(const struct dmi_system_id *dmi)
 {
        pr_info("Identified laptop model '%s'\n", dmi->ident);
@@ -411,6 +417,15 @@
                },
                .driver_data = &quirk_asus_forceals,
        },
+       {
+               .callback = dmi_matched,
+               .ident = "ASUSTeK COMPUTER INC. GA401IV",
+               .matches = {
+                       DMI_MATCH(DMI_SYS_VENDOR, "ASUSTeK COMPUTER INC."),
+                       DMI_MATCH(DMI_PRODUCT_NAME, "GA401IV"),
+               },
+               .driver_data = &quirk_asus_ga401iv,
+       },
        {},
 };
 

```

To applly it, use: `patch -p1 < /path/to/this/this.patch` within your kernel source direrctory. (only tested for 5.6.13)

And don't forget to run `echo 1 > /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy` to activate it. (I use a small oneshot service for that)

cheers.

**Comment by dragonnn** [comment]
@aspann can you make a dkms module for asus-nb-wmi? Would make easier to test changes in it.

**Comment by aspann** [comment]
Hi @dragonn,

sadly I'm not using DKMS and I'm still busy fixing the other things on G14 - so I don't have time to care a bout that at the moment. (Also this patch, is more a hack than a patch - btw. I'm using gentoo)

Maybe I can take care about a DKMS-Module at the end of the week. 


cheers.

**Comment by dragonnn** [comment]
Thanks, I will try it anyway, but I have GA401IU, so probably I need add a next position.

**Comment by aspann** [comment]
yep - but keep in mind, the important patch is only the first. (drivers/platform/x86/asus-wmi.c)
(which allows thee ACPI table to be populated with, for example, the thermalzone stuff)

The second (asus-nb-wmi) was just a "shot" to test if it got recognized via DMI.

**Comment by dragonnn** [comment]
Strange... I compiled the module with adding:
```
{
		.callback = dmi_matched,
		.ident = "ASUSTeK COMPUTER INC. GA401IV",
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "ASUSTeK COMPUTER INC."),
			DMI_MATCH(DMI_PRODUCT_NAME, "GA401IV"),
		},
		.driver_data = &quirk_asus_ga401iv,
	},
	{
		.callback = dmi_matched,
		.ident = "ASUSTeK COMPUTER INC. GA401IU",
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "ASUSTeK COMPUTER INC."),
			DMI_MATCH(DMI_PRODUCT_NAME, "GA401IU"),
		},
		.driver_data = &quirk_asus_ga401iu,
	},
```
And of course patching asus-wmi.c. But when I try loading the module I get:
```
modprobe: ERROR: could not insert 'asus_nb_wmi': No such device
```
I even checked if "asus-nb-wmi.ko" contains GA401IU with grep, and yes. Any idea?

**Comment by dragonnn** [comment]
In dmesg I get:
`i8042: PNP: No PS/2 controller found.`
WUT?

EDIT
I decided to remove everything with i8042 from the driver, since as I see only an asus_q500a is using it. After that the module loaded and I can change throttle_thermal_policy. This is a really big hack but it works. Strange is for me that you didn't have such problems.

**Comment by aspann** [comment]
I think this mapping is needed, because it ueses it as a filter. 
```c
.driver_data = &quirk_asus_ga401iu,
```
should be:
```
.driver_data = &quirk_asus_ga401iv,
```
or copy the quirk and adjust it. :)

[edit]:  
```bash
# grep -i i8042 /usr/src/linux/.config
CONFIG_SERIO_I8042=y
```

[edit2]:
If you want to, you can join my repo and we can have further discussions over [there](https://lab.retarded.farm/zappel/asus-rog-zephyrus-g14). (also a discord channel is avalibale if needed)


cheers.

**Comment by aspann** [comment]
updated version of the patch: [asus-wmi-kernel-5.6.13.patch](https://lab.retarded.farm/zappel/zGentoo/-/raw/master/sys-power/nvidia-ratchet-g14/files/asus-wmi-kernel-5.6.13.patch)

cheers.

**Comment by aspann** [comment]
okey, we got everything working. (except aniMe-matrix display)
see: https://lab.retarded.farm/zappel/asus-rog-zephyrus-g14

closing this now. 

cheers.
